/**
 * BLOCK 1: Data Scraping & Index Slicing
 * Located in the first 'Code in JavaScript' node.
 * Dynamically extracts company names and URLs from the target HTML structure
 * and slices the array to handle fault-tolerant workflow resume states.
 */
function parseAndSliceCompanies($input) {
    const html = $input.first().json.data;
    const regex = /<div class="firma_adi">\s*<a href="([^"]+)">([^<]+)<\/a>/g;
    const result = [];
    let match;

    // Scrape all companies into an array
    while ((match = regex.exec(html)) !== null) {
        result.push({
            json: {
                company: match[2].trim(),
                url: "[https://example-target-directory.com](https://example-target-directory.com)" + match[1]
            }
        });
    }

    // Advanced Resiliency Feature:
    // If the workflow crashes due to external API throttling (e.g., Google Sheets 429),
    // you can pass the last successful index here to resume without duplicate emails.
    const startIndex = 33; // Offset index for crash recovery
    return result.slice(startIndex);
}


/**
 * BLOCK 2: AI Response Sanitization & Error Handling
 * Located in the 'Code in JavaScript2' node.
 * Cleans markdown wrap-arounds from LLM payloads and safe-parses JSON properties.
 */
function sanitizeAiResponse($input) {
    let rawText = "";
    try {
        // Fallback checks for different n8n dynamic output models
        rawText = $input.first().json.text || 
                  $input.first().json.output?.[0]?.content?.[0]?.text || 
                  $input.first().json.message?.content || "";
    } catch (e) {
        rawText = "";
    }

    // Strip rogue markdown blocks commonly generated by OpenAI
    let cleanText = rawText.replace(/```json/gi, "").replace(/```/g, "").trim();
    let mailData = { subject: "", body: "" };

    // Graceful Degradation: If JSON parse fails, prevent workflow termination
    try {
        mailData = JSON.parse(cleanText);
    } catch (e) {
        mailData.subject = "Application for Engineering & Developer Positions";
        mailData.body = cleanText; // Fallback to raw text output
    }

    // Retrieve company metadata from upstream nodes
    const companyEmail = $('Code in JavaScript1').item.json.email;
    const companyName = $('Code in JavaScript1').item.json.company_name;

    return [{
        json: {
            company_name: companyName,
            to_email: companyEmail,
            subject: mailData.subject || "Application for Engineering & Developer Positions",
            body: mailData.body
        }
    }];
}